### ISSUE TITLE
problem serializing/deserializing using ''binary channel in UHDPerformance/Lite

### ISSUE THREAD

**Issue by billwoo** [TheCodeKing/XDMessaging.Net#13]
Win 10, VS 2017, .Net 4.7

The value the serialized Class in the  incoming message DataGram cast to TypedDataGram<Message> is not null, but trying to access its public fields throw's a null error.  Definition of the 'Message test  class appended at the end here.

I tried making the 'Message class implement 'ISerializable, but that made no difference. If I send the instance of 'Message to another channel, I get string data like this, which suggests the instance is getting serialized:

`AAEAAAD/////AQAAAAAAAAAMAgAAAD9NdWx0aUFwcCwgVmVyc2lvbj0xLjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPW51bGwFAQAAABBNdWx0aUFwcC5NZXNzYWdlAwAAAARGcm9tAlRvBFRleHQBAQECAAAABgMAAAAFaGVsbG8GBAAAAAhldmVyeW9uZQYFAAAAC29iamVjdCB0ZXN0CwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==`

Code that sends in WinForm App 1::
```
private void button1_Click(object sender, EventArgs e)
{
    // Send the object to a channel named binary
    // broadcaster.SendToChannel("binary", message);
    Message msg = new Message("hello","everyone", "object test");

    Mother.Broadcaster.SendToChannel("binary", msg);
}
```
Code that receives in WinForm App 2:
```
private void ListenerOnMessageReceived(Object sender, XDMessageEventArgs e)
{
    if (e.DataGram.Channel == "binary")
    {  
        TypedDataGram<Message> msg = e.DataGram;
        tbxTraffic.Text = "Binary: "; // ;
                
        tbxTraffic.AppendText("\r\ntext: " + msg.Message.Text + "\r\n");
        tbxTraffic.AppendText(msg.Message.To + "\r\n");
        tbxTraffic.AppendText(msg.Message.Text + "\r\n");
    }
}
```
Test Class:

```
using System;
using System.Runtime.Serialization;

namespace MultiApp
{
    [Serializable()]
    public class Message
    {
        public string From { set; get; }
        public string To { set; get; }
        public string Text { set; get; }

        public Message()
        {
        }

        public Message(String from, String to, String text) : this()
        {
            From = from;
            To = to;
            Text = text;
        }
    }
}
```

**Comment by TheCodeKing** [comment]
Sorry only just seen this. I've tried to reproduce with your code example, but not seeing any issues. Are you still seeing the problem?

**Comment by billwoo** [comment]
Going through some hardware problems here, and switching to VS 2017 Enterprise. 

Will get back to you in a few days.

thanks, Bill

**Comment by mayureshjadhav** [comment]
Any updates?

**Comment by billwoo** [comment]
@mayureshjadhav 

Try using the full library, not the 'Lite. And, forget doing binary serialization; I can't get that to work.

**Comment by TheCodeKing** [comment]
I had a look a while ago and couldn't reproduce. If you have any more info I can take another look. From what I understand the object is deserialized, but it's properties are null?

**Comment by TheCodeKing** [comment]
Closing as no response.
