### ISSUE TITLE
issues with latest version dl'd June 2019

### ISSUE THREAD

**Issue by billwoo** [TheCodeKing/XDMessaging.Net#16]

**Comment by billwoo** [comment]
1. running Messenger app in XDMessaging.Net-master\XDMessaging.Net-master\bin
a. warnings pop-up re absence of AWS credentials: "Azazon AWS crendentials not set. Enter your credentials in the app.config." **however, multiple instances of the app will work**.

2. opening XDMessaging solution in VS 2017/4.6.2: can't compile:

a.  The referenced component 'Conditions' could not be found.	XDMessaging.Demo	

**fixed by resetting the reference ...**	
	
b.  Application Configuration file "App.config" is invalid. Could not find file 'C:\Users\test_user\Desktop\XDMessaging.Net-master\XDMessaging.Net-master\src\XDMessaging.Demo\App.config'

**... fixed by opening the App.config,.template file, and saving a copy as 'App.config**

thanks, Bill

**Comment by TheCodeKing** [comment]
Sorry for the late response. Yes, the template is there an example and needs to be populated with settings.
