### ISSUE TITLE
XDMessaging - 2 messages received when 1 is sent

### ISSUE THREAD

**Issue by aslusser** [TheCodeKing/XDMessaging.Net#5]
Hi Mike,
Thanks for providing the xdmessaging dll. It works great.

I wanted to let you know about an issue I found when using your xdmessaging.dll when mcafee(see attached version info) is installed on one of my Computers.

Attached is a sample project I made to test the issue.

I have gotten around the issue by disabling virus scanning for the “c:\programdata\xdmessaging” folder and subfolders

![virus scan](https://cloud.githubusercontent.com/assets/10121359/5346817/9eeb7bee-7ef1-11e4-8151-22ee5dca71d0.png)

The issue is when I send 1 message, 2 are received.
I assume this has something to do with the virus scan checking the file, before or after it is created/modified.

I am also able to get around the issue by changing the transport method from IOStream to WindowsMessaging.

I think I can live with just disabling the viruscan for this folder, but if you have any  other suggestions I would appreciate it.

**Comment by TheCodeKing** [comment]
Please see if resolved in version 5.0.0. I've removed dynamic assembly loading which may have been causing an issue.
