### ISSUE TITLE
Encoding Problem

### ISSUE THREAD

**Issue by h82258652** [TheCodeKing/XDMessaging.Net#7]
Hey, I'm a Chinese and I love this repo, it makes easy to communication between applications.
But I found when I send some chinese text, the listener will get wrong text(seems like encoding problem).

I upload a demo here:
https://github.com/h82258652/XDMessagingEncodingProblemDemo
(run listener first and then run broadcaster to send a chinese text)

Enviroment:
Package: XDMessaging.Lite 5.0.1
OS: Win10 14393 x64
.Net Framework: 4.6.2

**Comment by TheCodeKing** [comment]
Thanks for raising this, prob a simple encoding issue. Does this only happen in Compatibility mode?

**Comment by TheCodeKing** [comment]
Fixed in 5.0.2.
