### ISSUE TITLE
HighPerformanceModeUI not working correctly

### ISSUE THREAD

**Issue by bbuerger** [TheCodeKing/XDMessaging.Net#9]
The HighPerformanceModeUI is very unreliable (Windows 10, WPF)
It is sometimes broadcasted only to the same thread, than another time only to another thread and sometimes not at all.
The Compatibility modes is working perfect even between different processes.

**Comment by TheCodeKing** [comment]
HighPerformanceModeUI uses hidden Windows to listen for Windows messages. I've tested it works on WFP, but it might be there is cases where it does no (especially Windows 10, as this was written before it was released).

Do you have any example code?

**Comment by bbuerger** [comment]
Sure, 
https://github.com/bbuerger/WPFPlayground

**Comment by TheCodeKing** [comment]
HighPerformanceUI is only available directly from within a Windows Form class or a WPF Window. It creates a uses a hidden NativeWindow which listens for low level Windows messages. 

As you are creating the listener in a ViewModel, this will only work in compatibility mode. If you were to move the listener to instantiate inside the WPF MainWindow code itself, then it should work.
